spring:
  application:
    name: IOTCloudSpring
  datasource:
    url: jdbc:mysql://localhost:3306/iotcloud?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
    ddl-auto: update
    show-sql: true
  jwt:
    secret: iRvjyRQmlF/1BvXz7TqH3jLSgw9jvxVLFrUR1Ou7ytQ=
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password:
      database: 0
      timeout: 10000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
        shutdown-timeout: 100ms

  redis:
    redisson:
      config: |
        singleServerConfig:
          address: "redis://127.0.0.1:6379"
          database: 0
        threads: 4
        nettyThreads: 4
server:
  port: 9000
  address: 0.0.0.0

anomaly:
  service:
    url: http://localhost:9100

wechat:
  appid:   wx5eeb767a9004cd92
  secret:  c36b38bd86d792625974559c70050ed6
  template-id:
    alarm: 8CDxXL-hbfw1bUXUwKp_my8S8ahEce7rB9T7C4SQ74A

# application.yml
#emqx:
#  api:
#    url:   http://1.94.32.220:8085/api/v4/nodes/emqx@127.0.0.1/auth_username_password
#    token: xsOWCEMkJOZA789AdHZcDIfjG8YU0ew9C5vuuzo9Bxeq9BP

#  ssl:
#    enabled: true
#    key-store: classpath:keystore.p12
#    key-store-password: 123456
#    key-store-type: PKCS12
