spring:
  application:
    name: IOTCloudSpring
  datasource:
    url: jdbc:mysql://localhost:3306/iotcloud?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: qrs
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
    ddl-auto: update
    show-sql: true
  jwt:
    secret: iRvjyRQmlF/1BvXz7TqH3jLSgw9jvxVLFrUR1Ou7ytQ=
  data:
    redis:
      host: 127.0.0.1         # Redis服务器地址
      port: 6379              # Redis服务器连接端口
      password:              # Redis服务器连接密码（默认为空）
      database: 0            # Redis数据库索引（默认为0）
      timeout: 10000ms       # 连接超时时间（毫秒）
      lettuce:
        pool:
          max-active: 8      # 连接池最大连接数（使用负值表示没有限制）
          max-idle: 8        # 连接池中的最大空闲连接
          min-idle: 0        # 连接池中的最小空闲连接
        shutdown-timeout: 100ms  # 客户端优雅关闭的等待时间
server:
  port: 9000
  address: 0.0.0.0

anomaly:
  service:
    url: http://localhost:9100

wechat:
  appid:   wx5eeb767a9004cd92
  secret:  c36b38bd86d792625974559c70050ed6
  template-id:
    alarm: YOUR_ALARM_TEMPLATE_ID
#  ssl:
#    enabled: true
#    key-store: classpath:keystore.p12
#    key-store-password: 123456
#    key-store-type: PKCS12
